spring:
  datasource:
    url: jdbc:postgresql://localhost:5432/farm_for_workers
    username: postgres
    password: postgre1488rp
    driver-class-name: org.postgresql.Driver

  kafka:
    bootstrap-servers: localhost:9092

server:
  port: 8082
