spring:
  datasource:
    url: jdbc:postgresql://localhost:5432/farm_for_workers
    username: postgres
    password: postgre1488rp
    driver-class-name: org.postgresql.Driver

  kafka:
    bootstrap-servers: localhost:9092

  data:
    redis:
      host: localhost
      port: 6379
      url: jdbc:redis://localhost:6379/1

token:
  signing:
    key: 53A73E5F1C4E0A2D3B5F2D784E6A1B423D6F247D1F6E5C3A596D635A75327855

server:
  port: 8083
